### ISSUE TITLE
Creating control along with attribute

### ISSUE THREAD

**Issue by Kraviecc** [camelCaseDave/xrm-mock#10]
Hello @camelCaseDave ,

I saw that you started migration of xrm-mock-generator into this project so I'm gonna put this issue/question here. Are you going to implement creating control along with creating attribute , ie. via `XrmMockGenerator.Attribute.createOptionSet` method? `Xrm.Page.getControl` is not working (it returns ` Cannot read property 'getName' of undefined` - in `    StandardControlMock.prototype.getName = function () {
        return this.control.getName();
    };`).

Have a nice day!

**Comment by camelCaseDave** [comment]
Hi @kraviecc. Yes, the generator should be very opinionated and default as many values as possible to closely mimic Xrm’s true implementation. Controls should be created when an Attribute is created.

**Comment by daryllabar** [comment]
I've fixed the issue with not being able to create the control from the Xrm-Mock-Generator already, just haven't published it (actually, I'm not sure how or when to publish it).  

I'm working on this issue today.

**Comment by daryllabar** [comment]
And as far as defaulting controls, I'm planning on having the Generator not require anything besides the type which is determined by the function name string/number/lookup, etc, and the name of the attribute/control.

**Comment by daryllabar** [comment]
This should be done now for all attribute types.
