### ISSUE TITLE
Should Interfaces Be Prefixed with "I"

### ISSUE THREAD

**Issue by daryllabar** [camelCaseDave/xrm-mock#12]
The Definitely Typed standard is to not preface interfaces with "I".  Didn't know if we wanted to follow that standard, or continue to use the "I" prefix?  I believe the reason they don't do it, is because pretty much everything could be an interface, so it get's a little verbose.

**Comment by camelCaseDave** [comment]
I don't think it's necessary. If the project is to stop, then even if tslint is downgraded from `latest` to `recommended` we'd still need to modify the rule `"interface-name"`.

**Comment by daryllabar** [comment]
Don't quite understand your comments..., so keep prefixing with "I"?

**Comment by camelCaseDave** [comment]
Yes keep prefixing with "I". In the future this may change, but at the moment the project is adhering to linting guidelines outlined in the project's [tslint.json](https://github.com/camelCaseDave/xrm-mock/blob/master/tslint.json).

**Comment by daryllabar** [comment]
Sounds Great!
