### ISSUE TITLE
3.0.0 didn't grab the latest code base

### ISSUE THREAD

**Issue by daryllabar** [camelCaseDave/xrm-mock#15]
I'm getting an error in my project due to this line of code in autolookupcontrol.mock.js
```javascript
var standardcontrol_mock_1 = require("./../standardcontrol/standardcontrol.mock");
```

Apparently my module loader doesn't like the "./.." syntax...  But the actual code base had/has this syntax:

```javascript
var standardcontrol_mock_1 = require("../standardcontrol/standardcontrol.mock");
```
So apparently, the methodology for building the npm package didn't generate the latest source...

**Comment by camelCaseDave** [comment]
Odd, running `npm pack` and inspecting autolookupcontrol.mock.js in the .tgz file, I can see it's using the latest source. Having said that, if I download v3.0.0 in a separate project I can see it's using older source.

I've run `npm publish` for a new v3.0.1 and downloaded that into a separate project. Looking at node_modules/xrm-mock/dist/xrm-mock/page/autolookupcontrol/autolookupcontrol.mock.js it's now correctly using `require("../standard..")

**Comment by daryllabar** [comment]
Looks Good!
