### ISSUE TITLE
ItemCollection.forEach modifies collection

### ISSUE THREAD

**Issue by daryllabar** [camelCaseDave/xrm-mock#17]
ForEach shouldn't modify the collection, just call the delegate for each item in the collection.  Currently it is mapping the delegate, and updating the collection to the results of the map.

**Comment by camelCaseDave** [comment]
Ah.. 
```typescript
public forEach(delegate: any): void {
    const modifiedCollection = this.itemCollection.map(delegate);
    this.itemCollection = modifiedCollection as any as T[];
}
```

This would explain the error I've been having with **processmanager.mock.ts** when calling `getActiveStage` and `setActiveStage` -- both functions use `forEach`.

**Comment by daryllabar** [comment]
I'm fixing it now.
