### ISSUE TITLE
Slow Loading time in unit tests

### ISSUE THREAD

**Issue by daryllabar** [camelCaseDave/xrm-mock#18]
Loading all of the files is taking almost 2 seconds... Looks like we should look to build it into a single file:

![image](https://user-images.githubusercontent.com/9728423/39925344-486602e4-54f9-11e8-8659-3126346506d5.png)

**Comment by camelCaseDave** [comment]
Is this resolved by #f2b761ed0677ed6795ef2f1ecde44f468d70f407?

**Comment by daryllabar** [comment]
I've added the build files to the npm package.  This solves my issue.
