### ISSUE TITLE
Context Mocks

### ISSUE THREAD

**Issue by roshangautam** [camelCaseDave/xrm-mock#23]
Any plans to add support for mocking GlobalContext , EventContext etc to be able to mock a form event with executionContext and mock currently logged in user? Any help would be highly appreciated :)

**Comment by daryllabar** [comment]
Plans?  Of course.  Time to do it?  Not yet.  :). We also need to define how to handle 8.0 context vs 9.0.  I'm guessing a config value somewhere...
