### ISSUE TITLE
How I can mock Form.FormType = 2 (update) with JS test

### ISSUE THREAD

**Issue by phuocle** [camelCaseDave/xrm-mock#26]
Our team use js test with this framework.

But we don't know how to mock the formType = 2 to check the form.

Please help me the example code.

Thanks.

**Comment by daryllabar** [comment]
Can you try this as a work around?

```
(XrmMockGenerator.formContext.ui.formSelector.getCurrentItem() as FormItemMock).formType = XrmEnum.FormType.Update;
```

We'll need to think if there is a better way to do this @camelCaseDave, like maybe just adding a property to the ```IXrmGeneratorComponents```, that get's passed to the ```createFormContext```, and then to the ```Ui.createUi()```` call

**Comment by phuocle** [comment]
I can set this mock:
```js
Xrm.Page.ui.formSelector.items.itemCollection[0].formType = 2;
```
After that, call: ```Xrm.Page.ui.getFormType()``` return ```2```

Thanks.

**Comment by skfd** [comment]
thank you for workaround, but it would be cooler to have special method. I'd try to contribute sometime, but need some API suggestions.
