### ISSUE TITLE
Open to contributions?

### ISSUE THREAD

**Issue by jordimontana82** [camelCaseDave/xrm-mock#3]
Hi Dave!

I've accidentally came across this repo after checking some of Jason Lattimer's one! :)

I'm running 2 open source projects for Unit testing Dynamics CRM. FakeXrmEasy and FakeXrmEasy.js. First one is pretty mature now and I'll be spending more time on the other one now for mocking web api calls. 

Was going to start a new repo for mocking the Xrm Page cause the only one I found was from Patrick Verbateen in CodePlex but it looks abandoned .... until I came across yours!

I think with your xrm mock project, plus the 2 FakeXrmEasy ones, then we're covered in terms of unit testing pretty much any CRM extension :)

**Comment by camelCaseDave** [comment]
Hi @jordimontana82,

Yes absolutely - I'd welcome collaboration and co-authors on this project

**Comment by jordimontana82** [comment]
Awesome! 👍

**Comment by camelCaseDave** [comment]
Hi again @jordimontana82. Just to update you, @daryllabar is now a collaborator on the project - we're discussing how to move the project forward [here on gitter](https://gitter.im/xrm-mock/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). If you're around, please jump in to have a chat!
