### ISSUE TITLE
`XrmMockGenerator.Control.createBool()` funciton not exist 

### ISSUE THREAD

**Issue by mishasmaga** [camelCaseDave/xrm-mock#33]
I have code in my function that I try test:
```
 Xrm.Page.getControl("zepcis_isbranch").setDisabled(true);
```
I init my XrmObjectModel :
```
  XrmMockGenerator.initialise();
           XrmMockGenerator.Attribute.createBool('zepcis_isbranch', true);
```
and when start testing then have exception:
```
FAILED TESTS:
  Company module
    Main form
      × test
        PhantomJS 2.1.1 (Windows 8 0.0.0)
      null is not an object (evaluating 'Xrm.Page.getControl('zepcis_isbranch').setDisabled')
      setAvailabilityLegalRelatedFields@tests/Entities/Company.spec.ts:9:615373
      OnLoad@tests/Entities/Company.spec.ts:9:608441
      tests/Entities/Company.spec.ts:9:231581

npm ERR! Test failed.  See above for more details.
```

but i haven't posibility create control with type bool. `XrmMockGenerator.Control.createBool()` function not exist.

**Comment by daryllabar** [comment]
The Boolean Attribute isn't setup to auto create controls, but it should be.

**Comment by mishasmaga** [comment]
@daryllabar, describe this distributed [.d.ts file](https://github.com/camelCaseDave/xrm-mock/blob/master/dist/xrm-mock-generator/control.d.ts) 

This issue fix in this [PR](https://github.com/camelCaseDave/xrm-mock/pull/32), but PR not completed.

**Comment by daryllabar** [comment]
3.4.8 should have this in it now.
