### ISSUE TITLE
Use strict versioning for @types/xrm

### ISSUE THREAD

**Issue by jordimontana82** [camelCaseDave/xrm-mock#38]
Hi Dave!

Hope all is ok! :) 

This is somehow related to #6 . 

At the minute trying to build the project against latest version of @types/xrm (9.0.14) breaks the build. However, running against version 9.0.7 works fine. 

I think we could use a strict versioning to be added to the dependencies of package.json (i.e. use exactly "9.0.7" instead of "^9.0.7") it would make it more obvious which version this project depends on. And so when we have a version of xrm-mock compatible with latest xrm/types we could upgrade the package accordingly and also any package depending on xrm-mock will use exactly the same.

**Comment by jordimontana82** [comment]
Same as #37 I guess

**Comment by jordimontana82** [comment]
![imagen](https://user-images.githubusercontent.com/3968950/61382743-a0acd280-a8ad-11e9-9531-06ecdd6fd3c4.png)

**Comment by camelCaseDave** [comment]
Thanks very much @jordimontana82. I was able to reproduce the issue building against 9.0.14.
