### ISSUE TITLE
Attribute fireOnChange

### ISSUE THREAD

**Issue by derekfinlinson** [camelCaseDave/xrm-mock#44]
The fireOnChange mock is passing in the attribute to any event handlers when it should be passing in the execution context. That makes it difficult to test onChange methods since you need that execution context to get a form context.

**Comment by camelCaseDave** [comment]
@derekfinlinson we recently implemented `Xrm.Utility.getGlobalContext()` by simply returning the `context` object property on `XrmMockGenerator`. We could do the same here and change the current attribute fireOnChange mock:

```ts
public fireOnChange(): void {
  if (this.eventHandlers.length) {
    for (const handler of this.eventHandlers) {
      handler.call(this);
    }
  }
}
```

To this:

```ts
public fireOnChange(): void {
  if (this.eventHandlers.length) {
    for (const handler of this.eventHandlers) {
      handler.call(XrmMockGenerator.context);
    }
  }
}
```

What do you think?

**Comment by derekfinlinson** [comment]
That would help with getting a form context but it really needs to be an `EventContext `object in case you're using `context.getEventSource()` to get the attribute for the onChange event. Which means you'll also need to be able to set that source in the context.

When I first noticed this last September I tried taking a stab at fixing it but wasn't exactly sure how to implement it. It does seem like you'll need to get the EventContext from the [XrmMockGenerator](https://github.com/camelCaseDave/xrm-mock/blob/97fcd6f5b4dbc49fd1d082c73d0be2f6a91c5d9b/src/xrm-mock-generator/xrm-mock-generator.ts#L19) into the [AttributeMock](https://github.com/camelCaseDave/xrm-mock/blob/97fcd6f5b4dbc49fd1d082c73d0be2f6a91c5d9b/src/xrm-mock/attributes/attribute/attribute.mock.ts#L36) file so you can set the source and then pass that as the parameter.

**Comment by LarsBauer** [comment]
Any update on this issue? Unfortunately this is a huge deal-breaker for xrm-mock... 😕
