### ISSUE TITLE
'addOnLoad' in type 'GridControlMock' is not assignable to the same property in base type 'GridControl'

### ISSUE THREAD

**Issue by korakanchan** [camelCaseDave/xrm-mock#45]
I am using following target packages :
 "@types/xrm": "9.0.7"
 "xrm-mock": "3.4.12",

When compiling the ts files I am getting the following errors:

Error	TS2416	(TS) Property 'addOnLoad' in type 'GridControlMock' is not assignable to the same property in base type 'GridControl'.
  Type '(handler: () => void) => void' is not assignable to type '(handler: ContextSensitiveHandler) => void'.
    Types of parameters 'handler' and 'handler' are incompatible.	
node_modules\xrm-mock\dist\xrm-mock\controls\gridcontrol\gridcontrol.mock.d.ts

Error	TS2416	(TS) Property 'body' in type 'ExecuteResponseMock' is not assignable to the same property in base type 'ExecuteResponse'.
  Type 'string' is not assignable to type 'ReadableStream<Uint8Array>'.	
node_modules\xrm-mock\dist\xrm-mock\executeresponse\executeresponse.mock.d.ts	

Error	TS2416	(TS) Property 'type' in type 'ExecuteResponseMock' is not assignable to the same property in base type 'ExecuteResponse'.
  Type 'string' is not assignable to type 'ResponseType'.	
node_modules\xrm-mock\dist\xrm-mock\executeresponse\executeresponse.mock.d.ts

**Comment by mikefactorial** [comment]
I'm having the same issue 
"@types/xrm": "9.0.18"
"xrm-mock": "3.4.16"
"typescript": "3.7.4" -- Tried going back as far as 3.5.3 with no success.

Updating the definitions to match the base types fixes it locally. Is there a recommended version of typescript and @types/xrm to use for the latest version of xrm-mock? It's likely I've missed something  obvious but thought I'd share.

The specific issues are:
1. In gridcontrol.mock.d.ts - handler should be typed as Xrm.Events.ContextSensitiveHandler
 a. Currently typed as handler: () => void
2. In executeresponse.mock.d.ts
 a. Current Definition for ExecuteResponseMock
     body: string;
     headers: any;
     ok: boolean;
     status: number;
     statusText: string;
     type: string;
     url: string;
    constructor(components: IExecuteResponseComponents);

 b. Members Required to Implement Xrm.ExecuteResponse (and Response / Body base classes)
     body: ReadableStream<Uint8Array>;
     headers: Headers;
     ok: boolean;
     redirected: boolean;
     status: number;
     statusText: string;
     type: ResponseType;
     url: string;
     trailer: Promise<Headers>;
     clone(): Response;

    bodyUsed: boolean;
    arrayBuffer(): Promise<ArrayBuffer>;
    blob(): Promise<Blob>;
    formData(): Promise<FormData>;
    json(): Promise<any>;
    text(): Promise<string>;

**Comment by camelCaseDave** [comment]
@mikefactorial good work. #49 includes the code you provided. I'll publish the new xrm-mock v3.4.17 now.

**Comment by mikefactorial** [comment]
Pulled the latest and everything works great. Thank you @camelCaseDave for a great framework!
