### ISSUE TITLE
Not working with latest @types/xrm

### ISSUE THREAD

**Issue by yannicksaenen** [camelCaseDave/xrm-mock#6]
Hi, it is not working with the latest @types/xrm.
It just needs a small fix.

**Comment by camelCaseDave** [comment]
Hi @yannicksaenen, xrm-mock is built to work against version 8.2 of `@types/xrm`. I'm open to ideas as to how we structure the project to work with multiple versions, specifically the new (and quite different) version 9.

**Comment by daryllabar** [comment]
It appears to be working for me using the 9.0 @types/xrm

**Comment by daryllabar** [comment]
I do have a local version that is using the 9.0 types.  There was one issue with the actually definitely typed definitions involving collections.  I've fixed it in the DT source, but it will take a while before it gets approved and published.  I can check in my local version of the Xrm @types, and once it does, just undo the check in, or I can wait to publish once the DT version is on npm.

Thoughts?
