### ISSUE TITLE
setVisible() do nothing

### ISSUE THREAD

**Issue by borutv** [camelCaseDave/xrm-mock#63]
Hi, I have something like this in my controller I would like to test:

 formContext.getAttribute("fieldName").controls.forEach(control => control.setVisible(true));

In my test I am setting this field like this:
  xrmMockGenerator.XrmMockGenerator.Attribute.createString({
          name: "fieldName", // Applies to all attributes
          value: false // Applies to all standard attributes, but type is attribute specific
        },
        [
          {
            visible: true
          }, {
            visible: false
          }
        ]
      );

function setVisible(true) do nothing. setDisabled(true) works just fine.

Please am I doing something wrong or? 

Thank you

**Comment by daryllabar** [comment]
I tried this, and it worked just fine:
```
  it("should handle visibility", () => {
    const label = XrmMockGenerator.Control.createString(StringAttributeMock.create("firstname"), "firstname", true, false, "First Name");
    label.setVisible(false);
    expect(label.getVisible()).toBe(false);
    label.setVisible(true);
    expect(label.getVisible()).toBe(true);
    label.setVisible(false);
    expect(label.getVisible()).toBe(false);
  });
```

Are you applying setVisible to an Attribute?  It is only for a control.

**Comment by daryllabar** [comment]
This appears to be working just fine.
