### ISSUE TITLE
Add empty lookup on form

### ISSUE THREAD

**Issue by romangobrey** [camelCaseDave/xrm-mock#87]
Hi,

I am trying to add an empty lookup on form using:
`XrmMockGenerator.Attribute.createLookup("parentaccountid", null);`

then I try to find it on form using:
```
var formContext = XrmMockGenerator.getEventContext().getFormContext();
var lookupAttribute = formContext.getAttribute("parentaccountid");
var lookupAttributeValue = lookupAttribute.getValue();
```

I expect null  ... **but it returns an empty array**
I checked behavior on real Dynamics form (tried both: v8.2 and v9.2) - lookup attribute is on the form but has no value - in both (v8.2 and v9.2) formContext.getAttribute().getValue() returns null as expected
**What am I missing?**
Thank you!

Here is the original code for .createLookup() call from xrm-mock package
![01](https://user-images.githubusercontent.com/19572565/222063567-c3685eee-15a2-4a6c-88be-4cd7febe9755.png)

![02](https://user-images.githubusercontent.com/19572565/222063602-c51d96fd-9e51-4c34-93b0-27975bea18e9.png)

**Comment by SPWareing** [comment]
Not sure if this solves the problem, but a workaround for returning a null value can be achieved by the following


```typescript
 const lookupMock = XrmMockGenerator.Attribute.createLookup("mock_id", [
      { id: "1234", entityType: "mock_entity" },
    ]);

lookupMock.getValue = jest.fn().mockReturnValue(null);
```
