### ISSUE TITLE
Contribution Guide/ Approach for the Wiki

### ISSUE THREAD

**Issue by maichopra** [camelCaseDave/xrm-mock#95]
I would like to add some additional pages and documentation the wiki, but I'm not sure how to go about it since there is no ability to edit the pages.

I was looking to update the pages with additional examples and add a new page to cover form and control notifications.

**Comment by daryllabar** [comment]
Can't you just fork it, make your suggestions, and create a PR?

**Comment by maichopra** [comment]
The wiki changes are in a separate repository and don't show when raise a PR.
Here is the updated wiki on my fork: https://github.com/maichopra/xrm-mock/wiki

This is what shows when I raise the PR from my fork.
![image](https://github.com/user-attachments/assets/333c4f2b-4aca-41eb-9c61-e48a8c700455)

**Comment by daryllabar** [comment]
I manually merged in the changes... next time maybe this might help?  https://stackoverflow.com/a/56480628/227436

Never had to worry about this before.  Thank you for your contribution

**Comment by maichopra** [comment]
Thanks for that.
Yep, never had to worry about the wiki repo before, but the link does make sense.

I just wish Github would allow you to raise PRs against the wiki repo, it would make things much easier.
